# Generated by Django 2.0.4 on 2018-05-01 14:12

import backend.storage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=600)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=600)),
                ('autor', models.CharField(max_length=100)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, to='storage.Category')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=600)),
                ('autor', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('publicado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('archivo_1', models.FileField(blank=True, upload_to=backend.storage.models.Item.directorio_files)),
                ('archivo_2', models.FileField(blank=True, upload_to=backend.storage.models.Item.directorio_files)),
                ('colecciones', models.ManyToManyField(blank=True, to='storage.Collection')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=600)),
                ('plataforma', models.CharField(blank=True, max_length=100, null=True)),
                ('instalar', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(blank=True, max_length=100, null=True)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=600)),
                ('dirigido_a', models.CharField(blank=True, max_length=100, null=True)),
                ('metadato_2', models.CharField(blank=True, max_length=100, null=True)),
                ('metadato_3', models.CharField(blank=True, max_length=100, null=True)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='storage.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Theme'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Item_type'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.Theme'),
        ),
    ]
