# Generated by Django 2.2.3 on 2019-07-20 21:08

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190720_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to=apps.article.models.Article.file_directory),
        ),
    ]
