# Generated by Django 2.2.3 on 2019-09-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190903_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
    ]
