# Generated by Django 2.2.3 on 2019-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_specification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collections',
            field=models.ManyToManyField(related_name='article_collections', to='collection.Collection'),
        ),
    ]
