# Generated by Django 3.0 on 2019-12-21 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(related_name='collection_categories', to='category.Category')),
                ('tags', models.ManyToManyField(related_name='collection_tags', to='tag.Tag')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_theme', to='theme.Theme')),
            ],
        ),
    ]
