# Generated by Django 2.2.3 on 2019-07-20 18:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theme', '0001_initial'),
        ('tag', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='category.Category')),
                ('tags', models.ManyToManyField(to='tag.Tag')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theme.Theme')),
            ],
        ),
    ]
