# Generated by Django 2.2.3 on 2019-08-19 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190720_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='categories',
            field=models.ManyToManyField(related_name='collection_categories', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(related_name='collection_tags', to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_theme', to='theme.Theme'),
        ),
    ]
