# Generated by Django 2.2.3 on 2019-08-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190819_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
